### ISSUE TITLE
Trace window chokes in RL

### ISSUE THREAD

**Issue by voigtjr** [soartech/jsoar#1] opened 2012-03-14 19:17 UTC
Reported by project member @daveray, Dec 3, 2008
What steps will reproduce the problem?
1. Run the water jugs RL with full tracing on

What is the expected output? What do you see instead?
Should see constantly scrolling trace output, possibly lagging behind
agent. Instead, the UI basically freezes.

Comment 1 by project member @daveray, Dec 9, 2008
Improved somewhat by more intelligently appending to the trace window. I think the
real solution is to implement a custom, append-only Document for the window.

**Comment by marinier** [comment] 2020-01-22 15:11
This may or may not be better now, based on more modern computers and also recent support for limiting the trace output in the debugger.

The current version of water jugs RL uses the gp command, which isn't implemented in jsoar yet. Probably it could be emulated with ngs4's templating mechanism, but I don't have the time to try that right now.

Given that the most likely solution would be some kind of custom UI widget, I'm closing this as the issue is not specific to RL, and if we decide that we need to address the trace window further, we can revisit in a new issue.

**Closed by marinier** 2020-01-22 15:11 UTC
Labels: bug
